version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]